service:
  name: contact-list-api

plugins:
- serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:PutItem
      - dynamodb:DeleteItem
      - dynamodb:UpdateItem
    Resource:
      - "Fn::GetAtt": [ ContactsTable, Arn ]

functions:
  getContacts:
    handler: dist/functions/getContacts.handler
    events:
      - http:
          method: get
          path: contact
  addContact:
    handler: dist/functions/addContact.handler
    events:
      - http:
          method: post
          path: contact
  deleteContact:
    handler: dist/functions/deleteContact.handler
    events:
      - http:
          method: delete
          path: contact/{id}

resources:
  - ${file(resources/dynamo-db.yml)}

package:
  artifact: ${opt:artifact}
  exclude:
    - ./**/*
  include:
    - dist/**/*.js
    - node_modules/**/*