Resources:
  ContactsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: contact-list
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE